# Generated by Django 5.2.6 on 2025-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelOptions(
            name='communitysubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='newsevent',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterField(
            model_name='community',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='communitysubmission',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
